# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: greenhouse.sap/v1alpha1
kind: ClusterPluginDefinition
metadata:
  name: kyverno-policies
spec:
  version: 1.2.2
  displayName: Kyverno
  description: Policies for Kyverno
  icon: https://raw.githubusercontent.com/cloudoperators/greenhouse-extensions/main/kyverno/logo.png
  helmChart:
    name: kyverno-policies
    repository: oci://ghcr.io/kengou4/greenhouse-extensions/charts
    version: 1.2.2
