apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: exempt-all-policies-for-siem-data-agents
  namespace: siem-data-agents
spec:
  exceptions:
  - policyName: "*"
    ruleNames:
    - "*"
  match:
    any:
    - resources:
        namespaces:
        - siem-data-agents